#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# heading     : Configuration
# description : DHCP Manager
# navigation  : 6000 6900
# 
# Copyright (c) 2003 Thierry Quaak  thierry@quaak.net
#               2014 Stephane de Labrusse stephdl@de-labrusse.fr
#----------------------------------------------------------------------

use strict;
use warnings;

use esmith::FormMagick::Panel::dhcpd;

my $f = esmith::FormMagick::Panel::dhcpd->new();
$f->display();

__DATA__
<form
    title="FORM_TITLE"
        header="/etc/e-smith/web/common/head.tmpl"
	footer="/etc/e-smith/web/common/foot.tmpl">
 	
	<page name="First" pre-event="print_status_message()">
		<description>DESCRIPTION_DHCPMANAGER</description>
        	<subroutine src="print_dhcpd()" />

	</page>
</form>

